services:
  postgres:
    image: postgres:17
    container_name: genquery-2.0
    restart: unless-stopped
    environment:
      POSTGRES_USER: analyst
      POSTGRES_PASSWORD: analyst@123
      POSTGRES_DB: ai_analyst
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
